# Generated by Django 3.0.7 on 2020-06-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='blog/images')),
                ('description', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=10)),
            ],
        ),
    ]
